# Generated by Django 3.2.9 on 2021-12-02 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(db_index=True, max_length=20, verbose_name='Last Name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Note')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
